<?php

function gigpress_programs($filter = null, $content = null) 
{

	global $wpdb;
	
    $atts = query_atts( // url query params
			shortcode_atts(
				array(
					'artist' => FALSE,
					'program_id' => FALSE,
					'exclude' => FALSE,
					'artist_order' => 'alpha',
					'genre' => FALSE
					), 
				$filter) );

	if($atts['artist'])
		$atts['program_id'] = $atts['artist'];
    $excluded_ids     = $atts['exclude'] ? explode(",",$atts['exclude']) : array();
    $selected_genres  = $atts['genre']   ? sanitize_text_field(explode(",",$atts['genre'])) : array();

	ob_start();
	
	include gigpress_template('artists-search-form');

	$query = "SELECT * FROM " . GIGPRESS_ARTISTS;
	$params = array();

	if( $atts['program_id'] )
	{
		$query .= ' where artist_id = %d' ;
		$params[] = $atts['program_id'];
	}
	else if ( $_SERVER['REQUEST_METHOD'] === 'POST' &&
              ! empty($_POST['search']) &&
              ! empty($_POST['gp_artist_search_nonce']) &&
                wp_verify_nonce($_POST['gp_artist_search_nonce'], 'gp_artist_search_action'))
 	{
	    $logic = (isset($_POST['logic']) 
	    			&& strtoupper($_POST['logic']) === 'AND')
			        ? 'AND'
			        : 'OR';
    	$search_note = !empty($_POST['search_note']);
    	
 		$search_string = sanitize_text_field( wp_unslash($_POST['search']) );
        // 1. Strip any slashes added by WordPress/PHP magic quotes
        // 2. Extract phrases in quotes OR individual words
        // PREG_SET_ORDER keeps the match groups tied to the specific hit
        preg_match_all('/"([^"]+)"|(\S+)/', $search_string, $matches, PREG_SET_ORDER);
        
        $terms = [];
        foreach ($matches as $match) 
        {
            // Index 1 is the inner content of " "
            // Index 2 is the standalone word
            $term = !empty($match[1]) ? $match[1] : $match[2];
            if ($term)
                $terms[] = $term;
        }

	    if ( ! empty($terms) ) 
	    {
		    $where_parts = array();
		
		    foreach ( $terms as $term ) 
		    {
		        $like = '%' . $wpdb->esc_like( $term ) . '%';
		        $where_parts[] = "(artist_name LIKE %s"
		        				 . ($search_note
		        				 	?	" OR program_notes LIKE %s)"
		        				 	:	")");
		        $params[] = $like;
		        if ( $search_note ) 
		            $params[] = $like;
		    }
		    $query .= " where " . implode(" $logic ", $where_parts);
	    }
 	}
	else
		echo $content;
		
	$query .= " ORDER BY " . ($atts['artist_order'] == 'custom'
					 ? "artist_order ASC" 
					 : "artist_alpha ASC");
	$query    = $wpdb->prepare( $query, ...$params );
	$programs = $wpdb->get_results($query);

	include gigpress_template('artists-list-start');
	
	if ( count($programs) > 0 )
	{
		foreach($programs as $program) 
		{
			if (in_array($program->artist_id, $excluded_ids))
				continue;

		    // Get existing genres for this program  
			require_once('../admin/handlers.php');
		    $program_genres = gigpress_get_program_genres($program->artist_id);
			if (empty(array_intersect($selected_genres,
										wp_list_pluck(
												$program_genres,
												"genre_slug"
									))))
				continue;
			
			$showdata = array();
			$showdata['artist']        = $program->artist_name;
			$showdata['artist_id']     = $program->artist_id;
			$showdata['artist_url']    = $program->artist_url;
			$showdata['program_notes'] = $program->program_notes;
			$showdata['genres']        = wp_list_pluck(
												$program_genres,
												"genre_name");
	
			include gigpress_template('artists-list');
		}
		include gigpress_template('artists-list-end');
	}
	
	echo('<!-- Generated by GigPress ' . GIGPRESS_VERSION . ' gigpress_programs -->
	');
	
	return ob_get_clean();	
}