<?php

function gigpress_programs($filter = null, $content = null) 
{

	global $wpdb, $gpo;
	$and_where = $limit = '';
	
	extract(shortcode_atts(array(
			'artist' => FALSE,
			'program_id' => FALSE,
			'exclude' => FALSE,
			'artist_order' => 'alpha'
		), $filter)
	);

	if($artist)
		$program_id = $artist;

	// Query vars take precedence over function vars
	if(isset($_GET['artist_id']))
		$program_id = $_GET['artist_id'];
	if(isset($_GET['program_id']))
		$program_id = $_GET['program_id'];
	if(isset($_GET['exclude']))
		$exclude = $_GET['exclude'];
	if(isset($_GET['artist_order']))
		$artist_order = $_GET['artist_order'];

	ob_start();
	
	include gigpress_template('artists-search-form');

	$query = "SELECT * FROM " . GIGPRESS_ARTISTS;
	$params = array();

	if( $program_id )
	{
		$query .= ' where artist_id = %d' ;
		$params[] = $program_id;
	}
	else if ( $_SERVER['REQUEST_METHOD'] === 'POST' &&
              ! empty($_POST['search']) &&
              ! empty($_POST['gp_artist_search_nonce']) &&
                wp_verify_nonce($_POST['gp_artist_search_nonce'], 'gp_artist_search_action'))
 	{
 		$search_string = sanitize_text_field( wp_unslash($_POST['search']) );

	    $logic = (isset($_POST['logic']) 
	    			&& strtoupper($_POST['logic']) === 'OR')
			        ? 'OR'
			        : 'AND';

    	$search_note = !empty($_POST['search_note']);
    	
	    $terms = preg_split('/\s+/', trim($search_string));
	    $terms = array_filter($terms);
	
	    if ( ! empty($terms) ) 
	    {
		    $where_parts = array();
		
		    foreach ( $terms as $term ) 
		    {
		        $like = '%' . $wpdb->esc_like( $term ) . '%';
		        $where_parts[] = "(artist_name LIKE %s"
		        				 . ($search_note
		        				 	?	" OR program_notes LIKE %s)"
		        				 	:	")");
		        $params[] = $like;
		        if ( $search_note ) 
		            $params[] = $like;
		    }
		    $query .= " where " . implode(" $logic ", $where_parts);
	    }
		else
		{
			unset($_POST['search']);
			echo $content;
		}
 	}
	else
		echo $content;
	
	$query .= " ORDER BY "
				  . ($artist_order == 'custom'
					 ? "artist_order ASC" 
					 : "artist_alpha ASC");
	$query    = $wpdb->prepare( $query, ...$params );
	$programs = $wpdb->get_results($query);

	if ( count($programs) == 0 )
		include gigpress_template('artists-list-empty');
	else
	{
     	if ($exclude)
    		$exclude = explode(",",$exclude);
    	else 
    		$exclude = array();

		include gigpress_template('artists-list-start');
		
		foreach($programs as $program) 
		{
			if (in_array($program->artist_id, $exclude))
				continue;
			$showdata = array();
			$showdata['artist']        = $program->artist_name;
			$showdata['artist_id']     = $program->artist_id;
			$showdata['artist_url']    = $program->artist_url;
			$showdata['program_notes'] = $program->program_notes;
	
			include gigpress_template('artists-list');
		}
		include gigpress_template('artists-list-end');
	}
	
	echo('<!-- Generated by GigPress ' . GIGPRESS_VERSION . ' gigpress_programs -->
	');
	
	return ob_get_clean();	
}